## 1. Realice las siguientes multiplicaciones matriz-matriz:

### a)

Una forma de realizar la multiplicación de matrices utilizando bucles anidados, donde la matriz resultante tendrá tantas filas como la primera matriz (A) y tantas columnas como la segunda matriz (B), y las matrices estaran dadas en forma de listas de listas

In [14]:
def multiplicar_matrices(A, B):
    # Verificar si las matrices son compatibles para la multiplicación
    if len(A[0]) != len(B):
        raise ValueError("El número de columnas de A debe ser igual al número de filas de B")

    # Inicializar la matriz resultante con ceros
    filas_A, columnas_A = len(A), len(A[0])
    filas_B, columnas_B = len(B), len(B[0])
    resultado = [[0 for _ in range(columnas_B)] for _ in range(filas_A)]

    # Realizar la multiplicación de matrices
    for i in range(filas_A):
        for j in range(columnas_B):
            for k in range(columnas_A):
                resultado[i][j] += A[i][k] * B[k][j]
    
    return resultado


# Ejemplo de uso
A = [[2, -3], 
     [3, -1]]

B = [[1, 5], 
     [2, 0]]

resultado = multiplicar_matrices(A, B)

print("Matriz resultado:")
for fila in resultado:
    print(fila)


Matriz resultado:
[-4, 10]
[1, 15]


Otra froma de realizar la multiplicación de matrices es utilizando NumPy, que es mucho más eficiente y simple

In [15]:
import numpy as np

A = np.array([[2, -3], 
              [3, -1]])

B = np.array([[1, 5], 
              [2, 0]])

resultado_a = np.dot(A, B)

print("Resultado de a):\n", resultado_a)


Resultado de a):
 [[-4 10]
 [ 1 15]]


### b)

In [16]:
A = np.array([[2, -3], [3, -1]])

B = np.array([[1, 5, -4], [-3, 2, 0]])

resultado_b = np.dot(A, B)

print("Resultado de b):\n", resultado_b)


Resultado de b):
 [[ 11   4  -8]
 [  6  13 -12]]


### c)

In [17]:
A = np.array([[2, -3, 1], [4, 3, 0], [5, 2, -4]])

B = np.array([[1, 0, 1, -2], [1, 0, -1, -1], [2, 3, -2, -2]])

resultado_c = np.dot(A, B)

print("Resultado de c):\n", resultado_c)


Resultado de c):
 [[  1   3   3  -3]
 [  7   0   1 -11]
 [ -1 -12  11  -4]]


### d)

In [18]:
A = np.array([[2, 1, 2], [-2, 3, 0], [2, -1, 3]])

B = np.array([[1, -2], [-4, 1], [0, 2]])

resultado_d = np.dot(A, B)

print("Resultado de d):\n", resultado_d)


Resultado de d):
 [[ -2   1]
 [-14   7]
 [  6   1]]


## 2.Determine cuáles de las siguientes matrices son no singulares y calcule la inversa de esas matrices: 

In [22]:
import numpy as np

def analizar_matriz(matriz):
    """
    Verifica si una matriz es no singular y, de serlo, calcula su inversa.

    Parámetros:
        matriz (numpy.ndarray): La matriz a analizar.

    Retorna:  Información sobre si la matriz es singular o no, y su inversa si aplica.
    """
    try:
        # Calcular el determinante
        determinante = np.linalg.det(matriz)
        resultado = f"Matriz:\n{matriz}\nDeterminante: {determinante:.2f}\n"

        # Verificar si la matriz es no singular
        if determinante != 0:
            inversa = np.linalg.inv(matriz)
            resultado += "La matriz es no singular.\nInversa:\n"
            resultado += f"{inversa}\n"
        else:
            resultado += "La matriz es singular y no tiene inversa.\n"

        return resultado

    except np.linalg.LinAlgError as e:
        return f"Error al analizar la matriz: {e}"



### a)

In [23]:
matrizA = np.array([[4, 2, 6], [3, 0, 7], [-2, -1, -3]])
resultado = analizar_matriz(matrizA)
print(resultado)

Matriz:
[[ 4  2  6]
 [ 3  0  7]
 [-2 -1 -3]]
Determinante: 0.00
La matriz es singular y no tiene inversa.



## b)

In [24]:
matrizB = np.array([[1, 2, 0], [2, 1, -1], [3, 1, 1]])
resultado = analizar_matriz(matrizB)
print(resultado)

Matriz:
[[ 1  2  0]
 [ 2  1 -1]
 [ 3  1  1]]
Determinante: -8.00
La matriz es no singular.
Inversa:
[[-0.25   0.25   0.25 ]
 [ 0.625 -0.125 -0.125]
 [ 0.125 -0.625  0.375]]



### c)

In [25]:
matrizC = np.array([[1, 1, -1, 1], [1, 2, -4, -2], [2, 1, 1, 5], [-1, 0, -2, -4]])
resultado = analizar_matriz(matrizC)
print(resultado)

Matriz:
[[ 1  1 -1  1]
 [ 1  2 -4 -2]
 [ 2  1  1  5]
 [-1  0 -2 -4]]
Determinante: 0.00
La matriz es singular y no tiene inversa.



### d)

In [26]:
matrizD = np.array([[4, 0, 0, 0], [6, 7, 0, 0], [9, 11, 1, 0], [5, 4, 1, 1]])
resultado = analizar_matriz(matrizD)
print(resultado)

Matriz:
[[ 4  0  0  0]
 [ 6  7  0  0]
 [ 9 11  1  0]
 [ 5  4  1  1]]
Determinante: 28.00
La matriz es no singular.
Inversa:
[[ 0.25        0.          0.          0.        ]
 [-0.21428571  0.14285714 -0.         -0.        ]
 [ 0.10714286 -1.57142857  1.         -0.        ]
 [-0.5         1.         -1.          1.        ]]



## 3.Resuelva los sistemas lineales 4 x 4 que tienen la misma matriz de coeficientes:

In [28]:
%load_ext autoreload

In [34]:
%autoreload 2
from src import (
    descomposicion_LU,
    resolver_LU
)

A = np.array([
    [1, -1, 2, -1],
    [1, 0, -1, 1],
    [2, 1, 3, -4],
    [0, -1, 1, -1]
])

b1 = np.array([6, 4, -2, 5])  
b2 = np.array([1, 1, 2, -1])  

# Descomposición LU
L, U = descomposicion_LU(A)

# Resolver el sistema
x1 = resolver_LU(L, U, b1)
x2 = resolver_LU(L, U, b2)

print("\nMatriz L:")
print(L)
print("\nMatriz U:")
print(U)
print("\nSolución del sistema 1:")
print(x1)
print("\nSolución del sistema 2:")
print(x2)

[01-23 19:16:33][INFO] 
[[ 1. -1.  2. -1.]
 [ 0.  1. -3.  2.]
 [ 0.  3. -1. -2.]
 [ 0. -1.  1. -1.]]
[01-23 19:16:33][INFO] 
[[ 1. -1.  2. -1.]
 [ 0.  1. -3.  2.]
 [ 0.  0.  8. -8.]
 [ 0.  0. -2.  1.]]
[01-23 19:16:33][INFO] 
[[ 1. -1.  2. -1.]
 [ 0.  1. -3.  2.]
 [ 0.  0.  8. -8.]
 [ 0.  0.  0. -1.]]
[01-23 19:16:33][INFO] 
[[ 1. -1.  2. -1.]
 [ 0.  1. -3.  2.]
 [ 0.  0.  8. -8.]
 [ 0.  0.  0. -1.]]
[01-23 19:16:33][INFO] Sustitución hacia adelante
[01-23 19:16:33][INFO] y = 
[[ 6.]
 [-2.]
 [-8.]
 [ 1.]]
[01-23 19:16:33][INFO] Sustitución hacia atrás
[01-23 19:16:33][INFO] i = 2
[01-23 19:16:33][INFO] suma = [8.]
[01-23 19:16:33][INFO] U[i, i] = 8.0
[01-23 19:16:33][INFO] y[i] = [-8.]
[01-23 19:16:33][INFO] i = 1
[01-23 19:16:33][INFO] suma = [4.]
[01-23 19:16:33][INFO] U[i, i] = 1.0
[01-23 19:16:33][INFO] y[i] = [-2.]
[01-23 19:16:33][INFO] i = 0
[01-23 19:16:33][INFO] suma = [3.]
[01-23 19:16:33][INFO] U[i, i] = 1.0
[01-23 19:16:33][INFO] y[i] = [6.]
[01-23 19:16:33][INFO] Sustituci

## 4. Encuentre los valores de A que hacen que la siguiente matriz sea singular.

In [27]:
import sympy as sp

alpha = sp.symbols('alpha')

A = sp.Matrix([
    [1, -1, alpha],
    [2, 2, 1],
    [0, alpha, -3/2]
])

det_A = A.det()
solutions = sp.solve(det_A, alpha)

print(f"Determinante de A: {det_A}")
print(f"Valores de alpha que hacen que A sea singular: {solutions}")

Determinante de A: 2*alpha**2 - alpha - 6.0
Valores de alpha que hacen que A sea singular: [-1.50000000000000, 2.00000000000000]


## 5.Resuelva los siguientes sistemas lineales:

In [50]:
L = np.array([[1, 0, 0],
     [2, 1, 0],
     [-1, 0, 1]])

U= np.array([[2, 3, -1],
    [0, -2, 1],
    [0, 0, 3]])

b = np.array([2, -1, 1])

x_a = resolver_LU(L, U, b)

print("\nSolución del sistema a:")
print(x_a)

[01-23 20:10:34][INFO] Sustitución hacia adelante
[01-23 20:10:34][INFO] y = 
[[ 2.]
 [-5.]
 [ 3.]]
[01-23 20:10:34][INFO] Sustitución hacia atrás
[01-23 20:10:34][INFO] i = 1
[01-23 20:10:34][INFO] suma = [1.]
[01-23 20:10:34][INFO] U[i, i] = -2
[01-23 20:10:34][INFO] y[i] = [-5.]
[01-23 20:10:34][INFO] i = 0
[01-23 20:10:34][INFO] suma = [8.]
[01-23 20:10:34][INFO] U[i, i] = 2
[01-23 20:10:34][INFO] y[i] = [2.]

Solución del sistema a:
[[-3.]
 [ 3.]
 [ 1.]]


In [52]:
L = np.array([[2, 0, 0],
              [-1, 1, 0],
              [3, 2, -1]])

U= np.array([[1, 1, 1],
             [0, 1, 2],
             [0, 0, 1]])

b = np.array([-1, 3, 0])

x_b = resolver_LU(L, U, b)

print("\nSolución del sistema b:")
print(x_b)

[01-23 20:14:02][INFO] Sustitución hacia adelante
[01-23 20:14:02][INFO] y = 
[[-0.5]
 [ 2.5]
 [ 3.5]]
[01-23 20:14:02][INFO] Sustitución hacia atrás
[01-23 20:14:02][INFO] i = 1
[01-23 20:14:02][INFO] suma = [7.]
[01-23 20:14:02][INFO] U[i, i] = 1
[01-23 20:14:02][INFO] y[i] = [2.5]
[01-23 20:14:02][INFO] i = 0
[01-23 20:14:02][INFO] suma = [-1.]
[01-23 20:14:02][INFO] U[i, i] = 1
[01-23 20:14:02][INFO] y[i] = [-0.5]

Solución del sistema b:
[[ 0.5]
 [-4.5]
 [ 3.5]]


## 6. Factorice las siguientes matrices en la descomposición LU mediante el algoritmo de factorización LU con $lii = 1$ para todas las $i$

In [42]:
A_a = [[2, -1, 1],
       [3, 3, 9],
       [3, 3, 5]]

# Descomposición LU
L, U = descomposicion_LU(A_a)

print("\nFactorización LU de la matriz a:")
print("\nMatriz L:")
print(L)
print("\nMatriz U:")
print(U)

[01-23 19:50:21][INFO] 
[[ 2.  -1.   1. ]
 [ 0.   4.5  7.5]
 [ 0.   4.5  3.5]]
[01-23 19:50:22][INFO] 
[[ 2.  -1.   1. ]
 [ 0.   4.5  7.5]
 [ 0.   0.  -4. ]]
[01-23 19:50:22][INFO] 
[[ 2.  -1.   1. ]
 [ 0.   4.5  7.5]
 [ 0.   0.  -4. ]]

Factorización LU de la matriz a:

Matriz L:
[[1.  0.  0. ]
 [1.5 1.  0. ]
 [1.5 1.  1. ]]

Matriz U:
[[ 2.  -1.   1. ]
 [ 0.   4.5  7.5]
 [ 0.   0.  -4. ]]


In [39]:
A_b = [[1.012, -2.132, 3.104],
       [-2.132, 4.096, -7.013],
       [3.104, -7.013, 0.014]]

# Descomposición LU
L, U = descomposicion_LU(A_b)
print("\nFactorización LU de la matriz b:")
print("\nMatriz L:")
print(L)
print("\nMatriz U:")
print(U)

[01-23 19:49:51][INFO] 
[[ 1.012      -2.132       3.104     ]
 [ 0.         -0.39552569 -0.47374308]
 [ 0.         -0.47374308 -9.50656917]]
[01-23 19:49:51][INFO] 
[[ 1.012      -2.132       3.104     ]
 [ 0.         -0.39552569 -0.47374308]
 [ 0.          0.         -8.93914077]]
[01-23 19:49:51][INFO] 
[[ 1.012      -2.132       3.104     ]
 [ 0.         -0.39552569 -0.47374308]
 [ 0.          0.         -8.93914077]]

Factorización LU de la matriz b:

Matriz L:
[[ 1.          0.          0.        ]
 [-2.10671937  1.          0.        ]
 [ 3.06719368  1.19775553  1.        ]]

Matriz U:
[[ 1.012      -2.132       3.104     ]
 [ 0.         -0.39552569 -0.47374308]
 [ 0.          0.         -8.93914077]]


In [40]:
A_c = [[2, 0, 0, 0],
       [1, 1.5, 0, 0],
       [0, -3, 0.5, 0],
       [2, -2, 1, 1]]

# Descomposición LU
L, U = descomposicion_LU(A_c)
print("\nFactorización LU de la matriz c:")
print("\nMatriz L:")
print(L)
print("\nMatriz U:")
print(U)

[01-23 19:49:53][INFO] 
[[ 2.   0.   0.   0. ]
 [ 0.   1.5  0.   0. ]
 [ 0.  -3.   0.5  0. ]
 [ 0.  -2.   1.   1. ]]
[01-23 19:49:53][INFO] 
[[2.  0.  0.  0. ]
 [0.  1.5 0.  0. ]
 [0.  0.  0.5 0. ]
 [0.  0.  1.  1. ]]
[01-23 19:49:53][INFO] 
[[2.  0.  0.  0. ]
 [0.  1.5 0.  0. ]
 [0.  0.  0.5 0. ]
 [0.  0.  0.  1. ]]
[01-23 19:49:53][INFO] 
[[2.  0.  0.  0. ]
 [0.  1.5 0.  0. ]
 [0.  0.  0.5 0. ]
 [0.  0.  0.  1. ]]

Factorización LU de la matriz c:

Matriz L:
[[ 1.          0.          0.          0.        ]
 [ 0.5         1.          0.          0.        ]
 [ 0.         -2.          1.          0.        ]
 [ 1.         -1.33333333  2.          1.        ]]

Matriz U:
[[2.  0.  0.  0. ]
 [0.  1.5 0.  0. ]
 [0.  0.  0.5 0. ]
 [0.  0.  0.  1. ]]


In [41]:
A_d = [[2.1756, 4.0231, -2.1732, 5.1967],
       [-4.0231, 6.0000, 0, 1.1973],
       [-1.0000, -5.2107, 1.1111, 0],
       [6.0235, 7.0000, 0, -4.1561]]

# Descomposición LU
L, U = descomposicion_LU(A_d)
print("\nFactorización LU de la matriz d:")
print("\nMatriz L:")
print(L)
print("\nMatriz U:")
print(U)

[01-23 19:49:56][INFO] 
[[  2.1756       4.0231      -2.1732       5.1967    ]
 [  0.          13.43948042  -4.01866194  10.80699101]
 [  0.          -3.36150897   0.11220314   2.38862842]
 [  0.          -4.13860216   6.01685521 -18.54400331]]
[01-23 19:49:56][INFO] 
[[ 2.17560000e+00  4.02310000e+00 -2.17320000e+00  5.19670000e+00]
 [ 0.00000000e+00  1.34394804e+01 -4.01866194e+00  1.08069910e+01]
 [ 0.00000000e+00  4.44089210e-16 -8.92952394e-01  5.09169403e+00]
 [ 0.00000000e+00  0.00000000e+00  4.77933394e+00 -1.52160595e+01]]
[01-23 19:49:56][INFO] 
[[ 2.17560000e+00  4.02310000e+00 -2.17320000e+00  5.19670000e+00]
 [ 0.00000000e+00  1.34394804e+01 -4.01866194e+00  1.08069910e+01]
 [ 0.00000000e+00  4.44089210e-16 -8.92952394e-01  5.09169403e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.20361280e+01]]
[01-23 19:49:56][INFO] 
[[ 2.17560000e+00  4.02310000e+00 -2.17320000e+00  5.19670000e+00]
 [ 0.00000000e+00  1.34394804e+01 -4.01866194e+00  1.08069910e+01]
 [ 0.000000

## 7. Modifique el algoritmo de eliminación gaussiana de tal forma que se pueda utilizar para resolver un sistema lineal usando la descomposición LU y, a continuación, resuelva los siguientes sistemas lineales.

In [64]:
import numpy as np

def lu_decomposition(a):
    n = len(a)
    L = np.zeros((n, n))
    U = np.zeros((n, n))

    for i in range(n):
        # Calcula la matriz U
        for k in range(i, n):
            suma = sum(L[i][j] * U[j][k] for j in range(i))
            U[i][k] = a[i][k] - suma

        for k in range(i, n):
            if i == k:
                L[i][i] = 1  
            else:
                suma = sum(L[k][j] * U[j][i] for j in range(i))
                L[k][i] = (a[k][i] - suma) / U[i][i]

    return L, U

def forward_substitution(L, b):
    n = len(b)
    y = np.zeros(n)
    for i in range(n):
        y[i] = (b[i] - sum(L[i][j] * y[j] for j in range(i))) / L[i][i]
    return y

def backward_substitution(U, y):
    n = len(y)
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = (y[i] - sum(U[i][j] * x[j] for j in range(i + 1, n))) / U[i][i]
    return x

def solve_lu(a, b):
    L, U = lu_decomposition(a)
    y = forward_substitution(L, b)
    x = backward_substitution(U, y)
    return x


### a.

In [73]:
A=np.array([[2, -1, 1],
            [3, 3, 9],
            [3, 3, 5]], dtype=float)

b= np.array([-1, 0, 4], dtype=float)

# Descomposición LU
L, U = descomposicion_LU_modificada(A)
# Resolver el sistema
x = solve_lu(A, b)

print("Solución del sistema a:")
print(x)

Solución del sistema a:
[ 1.  2. -1.]


### b.

In [72]:
A=np.array([
            [1.012, -2.132, 3.104],
            [-2.132, 4.096, -7.013],
            [3.104, -7.013, 0.014]
        ])

b= np.array([1.984, -5.049, -3.895])

# Descomposición LU
L, U = descomposicion_LU_modificada(A)
# Resolver el sistema
x = solve_lu(A, b)

print("Solución del sistema b:")
print(x)

Solución del sistema b:
[1. 1. 1.]


### c.

In [71]:
A=np.array([
            [2, 0, 0, 0],
            [1, 1.5, 0, 0],
            [0, -3, 0.5, 0],
            [0, -2, 1, 1]
        ])

b= np.array([3, 4.5, -6.6, 0.8])

# Descomposición LU
L, U = descomposicion_LU_modificada(A)
# Resolver el sistema
x = solve_lu(A, b)

print("Solución del sistema c:")
print(x)

Solución del sistema c:
[ 1.5  2.  -1.2  6. ]


### d.

In [70]:
A=np.array([
            [2.1756, 4.0231, -2.1732, 5.1967],
            [-4.0231, 6.0000, 0, 1.1973],
            [-1.0000, -5.2107, 1.1111, 0],
            [6.0235, 7.0000, 0, -4.1561]
        ])

b= np.array([17.102, -6.1593, 3.0004, 0])

# Descomposición LU
L, U = descomposicion_LU_modificada(A)
# Resolver el sistema
x = solve_lu(A, b)

print("Solución del sistema d:")
print(x)

Solución del sistema d:
[2.9398512  0.0706777  5.67773512 4.37981223]
